list: $/renick/survey/models/survey/columns.yaml
modelClass: Renick\Survey\Models\Survey
title: 'renick.survey::lang.plugin.name'
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: false
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'renick/survey/surveycontroller/preview/:id'
